version: '2'
services:
  zoo1:
    image: zookeeper
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888

  nifi-nodes:
    build: ./nifi-node
    image: nifi-node:1.0.0
    depends_on:
      - zoo1
    environment:
      - EXCLUDE_PORTS=8081,8082
      # Used by ListenTCP or other processors. Depends on the data flow.
      - TCP_PORTS=9001

  lb:
    image: dockercloud/haproxy
    links:
      - nifi-nodes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "9001:9001"
